### ISSUE TITLE
Real Time Video

### ISSUE THREAD

**Issue by lutfirz** [daedalus-tech/mc-mot#3]
Can we use this for real time video capture and how?

**Comment by mbenencase** [comment]
@lutfirz not sure if I understood your question, if you're looking for a real-time video capture, you can use OpenCV library (available in Python and C++) and use:

```[python]
cap = cv2.VideoCapture(path/to/your/video)
```

```[cpp]
cv::VideoCapture cap;
cap.open(path/to/your/video);
```

You can also provide RTSP URL as well.

However, if your question was in the sense of: is it possible to use the algorithm implemented in the repository for a real-time application?

The answer is: depends on your hardware. We used a NVIDIA GeForce 3060 Laptop GPU. It is, probably, possible to run on a Jetson Xavier NX or Jetson Xavier AGX. It might run in a Thundercomm EB5 AI-Box as well. However, we don't have any benchmarks for those.
